#############################################################################
# Makefile for building: release/8755prg.app/Contents/MacOS/8755prg
# Generated by qmake (3.1) (Qt 6.8.0)
# Project:  8755prg.pro
# Template: app
# Command: /usr/local/Qt-6.8.0/bin/qmake -o Makefile 8755prg.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_WARNING_OUTPUT -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk -mmacosx-version-min=12.0 -w $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk -mmacosx-version-min=12.0 -w $(DEFINES)
INCPATH       = -I. -I. -IGeneratedFiles -I$(QTDIR64)/include -I$(QTDIR64)/include/QtCore -I$(QTDIR64)/include/QtGui -I$(QTDIR64)/include/QtSerialPort -I$(QTDIR64)/include/QtWidgets -I/usr/local/Qt-6.8.0/lib/QtWidgets.framework/Headers -I/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers -I/usr/local/Qt-6.8.0/lib/QtSerialPort.framework/Headers -I/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers -IGeneratedFiles -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/System/Library/Frameworks/AGL.framework/Headers -IGeneratedFiles -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Qt-6.8.0/mkspecs/macx-clang -F/usr/local/Qt-6.8.0/lib
QMAKE         = /usr/local/Qt-6.8.0/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/Qt-6.8.0/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/Qt-6.8.0/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = 8755prg1.0.0
DISTDIR = /Users/keith/source/8755prg/release/8755prg1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk -mmacosx-version-min=12.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/usr/local/Qt-6.8.0/lib
LIBS          = $(SUBLIBS) -F/usr/local/Qt-6.8.0/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtSerialPort -framework QtCore -framework IOKit -framework DiskArbitration -framework UniformTypeIdentifiers -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = release/

####### Files

SOURCES       = hexFile.cpp \
		guiMainWindow.cpp \
		main.cpp \
		qLedWidget.cpp \
		senderthread.cpp GeneratedFiles/moc_guiMainWindow.cpp \
		GeneratedFiles/moc_qLedWidget.cpp \
		GeneratedFiles/moc_senderthread.cpp
OBJECTS       = release/hexFile.o \
		release/guiMainWindow.o \
		release/main.o \
		release/qLedWidget.o \
		release/senderthread.o \
		release/moc_guiMainWindow.o \
		release/moc_qLedWidget.o \
		release/moc_senderthread.o
DIST          = /usr/local/Qt-6.8.0/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/device_config.prf \
		/usr/local/Qt-6.8.0/mkspecs/common/unix.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/mac.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/macx.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/sanitize.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/clang.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/clang-mac.conf \
		/usr/local/Qt-6.8.0/mkspecs/qconfig.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_ext_freetype.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_ext_libjpeg.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_ext_libpng.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_ext_openxr_loader.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_freetype_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_graphs.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_graphs_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_graphswidgets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_graphswidgets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_grpc.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_grpc_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_grpcquick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_grpcquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_httpserver_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_jpeg_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_openxr_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_png_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_protobuf.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_protobuf_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_protobufquick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_protobufquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dxr.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/usr/local/Qt-6.8.0/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/qt_config.prf \
		/usr/local/Qt-6.8.0/mkspecs/macx-clang/qmake.conf \
		/usr/local/Qt-6.8.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt-6.8.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/toolchain.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/toolchain.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/default_pre.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/default_post.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/warn_off.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/permissions.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/qt.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/resources_functions.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/resources.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/moc.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/uic.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/mac.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/qmake_use.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/file_copies.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/rez.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/exceptions.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/yacc.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/lex.prf \
		8755prg.pro hexFile.h \
		guiMainWindow.h \
		qLedWidget.h \
		senderthread.h hexFile.cpp \
		guiMainWindow.cpp \
		main.cpp \
		qLedWidget.cpp \
		senderthread.cpp
QMAKE_TARGET  = 8755prg
DESTDIR       = release/
TARGET        = release/8755prg.app/Contents/MacOS/8755prg

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 15.2
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/keith/source/8755prg/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/keith/source/8755prg/8755prg.pro


include /usr/local/Qt-6.8.0/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

release/8755prg.app/Contents/MacOS/8755prg: GeneratedFiles/ui_guiMainWindow.h $(OBJECTS)  
	@test -d release/8755prg.app/Contents/MacOS/ || mkdir -p release/8755prg.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 8755prg.pro /usr/local/Qt-6.8.0/mkspecs/macx-clang/qmake.conf /usr/local/Qt-6.8.0/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/device_config.prf \
		/usr/local/Qt-6.8.0/mkspecs/common/unix.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/mac.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/macx.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/sanitize.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/clang.conf \
		/usr/local/Qt-6.8.0/mkspecs/common/clang-mac.conf \
		/usr/local/Qt-6.8.0/mkspecs/qconfig.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_ext_freetype.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_ext_libjpeg.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_ext_libpng.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_ext_openxr_loader.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_freetype_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_graphs.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_graphs_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_graphswidgets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_graphswidgets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_grpc.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_grpc_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_grpcquick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_grpcquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_httpserver_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_jpeg_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_openxr_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_png_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_protobuf.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_protobuf_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_protobufquick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_protobufquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dxr.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/usr/local/Qt-6.8.0/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/qt_config.prf \
		/usr/local/Qt-6.8.0/mkspecs/macx-clang/qmake.conf \
		/usr/local/Qt-6.8.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt-6.8.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/toolchain.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/toolchain.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/default_pre.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/default_post.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/warn_off.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/permissions.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/qt.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/resources_functions.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/resources.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/moc.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/uic.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/mac.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/qmake_use.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/file_copies.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/rez.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/exceptions.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/yacc.prf \
		/usr/local/Qt-6.8.0/mkspecs/features/lex.prf \
		8755prg.pro \
		/usr/local/Qt-6.8.0/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/Qt-6.8.0/lib/QtSerialPort.framework/Resources/QtSerialPort.prl \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile 8755prg.pro
/usr/local/Qt-6.8.0/mkspecs/features/spec_pre.prf:
/usr/local/Qt-6.8.0/mkspecs/features/device_config.prf:
/usr/local/Qt-6.8.0/mkspecs/common/unix.conf:
/usr/local/Qt-6.8.0/mkspecs/common/mac.conf:
/usr/local/Qt-6.8.0/mkspecs/common/macx.conf:
/usr/local/Qt-6.8.0/mkspecs/common/sanitize.conf:
/usr/local/Qt-6.8.0/mkspecs/common/gcc-base.conf:
/usr/local/Qt-6.8.0/mkspecs/common/gcc-base-mac.conf:
/usr/local/Qt-6.8.0/mkspecs/common/clang.conf:
/usr/local/Qt-6.8.0/mkspecs/common/clang-mac.conf:
/usr/local/Qt-6.8.0/mkspecs/qconfig.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_ext_freetype.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_ext_libjpeg.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_ext_libpng.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_ext_openxr_loader.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_chartsqml_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_coap.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_coap_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_core5compat.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_datavisualizationqml.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_declarativeopcua.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_freetype_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_graphs.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_graphs_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_graphswidgets.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_graphswidgets_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_grpc.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_grpc_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_grpcquick.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_grpcquick_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_harfbuzz_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_httpserver.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_httpserver_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_jpeg_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_jsonrpc_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsplatform.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsplatform_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labssettings.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_languageserver_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_linguist.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_mqtt.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_mqtt_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_opcua.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_opcua_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_openxr_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_png_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_protobuf.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_protobuf_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_protobufquick.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_protobufquick_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlls_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlmeta.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlmeta_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlnetwork.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dphysics.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dxr.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick3dxr_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickvectorimage.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_scxmlqml.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_shadertools.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_statemachine.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_statemachine_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_statemachineqml.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_tools_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_webchannelquick.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_webchannelquick_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
/usr/local/Qt-6.8.0/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
/usr/local/Qt-6.8.0/mkspecs/features/qt_functions.prf:
/usr/local/Qt-6.8.0/mkspecs/features/qt_config.prf:
/usr/local/Qt-6.8.0/mkspecs/macx-clang/qmake.conf:
/usr/local/Qt-6.8.0/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Qt-6.8.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-6.8.0/mkspecs/features/mac/sdk.prf:
/usr/local/Qt-6.8.0/mkspecs/features/toolchain.prf:
/usr/local/Qt-6.8.0/mkspecs/features/mac/toolchain.prf:
/usr/local/Qt-6.8.0/mkspecs/features/default_pre.prf:
/usr/local/Qt-6.8.0/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt-6.8.0/mkspecs/features/resolve_config.prf:
/usr/local/Qt-6.8.0/mkspecs/features/default_post.prf:
/usr/local/Qt-6.8.0/mkspecs/features/mac/default_post.prf:
/usr/local/Qt-6.8.0/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt-6.8.0/mkspecs/features/unix/thread.prf:
/usr/local/Qt-6.8.0/mkspecs/features/warn_off.prf:
/usr/local/Qt-6.8.0/mkspecs/features/permissions.prf:
/usr/local/Qt-6.8.0/mkspecs/features/qt.prf:
/usr/local/Qt-6.8.0/mkspecs/features/resources_functions.prf:
/usr/local/Qt-6.8.0/mkspecs/features/resources.prf:
/usr/local/Qt-6.8.0/mkspecs/features/moc.prf:
/usr/local/Qt-6.8.0/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-6.8.0/mkspecs/features/uic.prf:
/usr/local/Qt-6.8.0/mkspecs/features/mac/mac.prf:
/usr/local/Qt-6.8.0/mkspecs/features/qmake_use.prf:
/usr/local/Qt-6.8.0/mkspecs/features/file_copies.prf:
/usr/local/Qt-6.8.0/mkspecs/features/mac/rez.prf:
/usr/local/Qt-6.8.0/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Qt-6.8.0/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-6.8.0/mkspecs/features/exceptions.prf:
/usr/local/Qt-6.8.0/mkspecs/features/yacc.prf:
/usr/local/Qt-6.8.0/mkspecs/features/lex.prf:
8755prg.pro:
/usr/local/Qt-6.8.0/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/Qt-6.8.0/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/Qt-6.8.0/lib/QtSerialPort.framework/Resources/QtSerialPort.prl:
/usr/local/Qt-6.8.0/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile 8755prg.pro

qmake_all: FORCE

release/8755prg.app/Contents/PkgInfo: 
	@test -d release/8755prg.app/Contents || mkdir -p release/8755prg.app/Contents
	@$(DEL_FILE) release/8755prg.app/Contents/PkgInfo
	@echo "APPL????" > release/8755prg.app/Contents/PkgInfo
release/8755prg.app/Contents/Info.plist: 
	@test -d release/8755prg.app/Contents || mkdir -p release/8755prg.app/Contents
	@$(DEL_FILE) release/8755prg.app/Contents/Info.plist
	@plutil -convert xml1 -o - /usr/local/Qt-6.8.0/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.peardrop.co.uk.8755prg,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.peardrop.co.uk.8755prg,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},12.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,8755prg,g" -e "s,@LIBRARY@,8755prg,g" -e "s,\$${EXECUTABLE_NAME},8755prg,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >release/8755prg.app/Contents/Info.plist

all: Makefile \
		release/8755prg.app/Contents/PkgInfo \
		release/8755prg.app/Contents/Info.plist release/8755prg.app/Contents/MacOS/8755prg

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Qt-6.8.0/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents hexFile.h guiMainWindow.h qLedWidget.h senderthread.h $(DISTDIR)/
	$(COPY_FILE) --parents hexFile.cpp guiMainWindow.cpp main.cpp qLedWidget.cpp senderthread.cpp $(DISTDIR)/
	$(COPY_FILE) --parents guiMainWindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r release/8755prg.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: GeneratedFiles/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) GeneratedFiles/moc_predefs.h
GeneratedFiles/moc_predefs.h: /usr/local/Qt-6.8.0/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk -mmacosx-version-min=12.0 -w -dM -E -o GeneratedFiles/moc_predefs.h /usr/local/Qt-6.8.0/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: GeneratedFiles/moc_guiMainWindow.cpp GeneratedFiles/moc_qLedWidget.cpp GeneratedFiles/moc_senderthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) GeneratedFiles/moc_guiMainWindow.cpp GeneratedFiles/moc_qLedWidget.cpp GeneratedFiles/moc_senderthread.cpp
GeneratedFiles/moc_guiMainWindow.cpp: guiMainWindow.h \
		GeneratedFiles/ui_guiMainWindow.h \
		hexFile.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qstring.h \
		senderthread.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QMutex \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qmutex.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QThread \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QWaitCondition \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qwaitcondition.h \
		qLedWidget.h \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers/QPainter \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers/qpainter.h \
		GeneratedFiles/moc_predefs.h \
		/usr/local/Qt-6.8.0/libexec/moc
	/usr/local/Qt-6.8.0/libexec/moc $(DEFINES) --include /Users/keith/source/8755prg/GeneratedFiles/moc_predefs.h -I/usr/local/Qt-6.8.0/mkspecs/macx-clang -I/Users/keith/source/8755prg -I/Users/keith/source/8755prg -I/Users/keith/source/8755prg/GeneratedFiles -I'/Users/keith/source/8755prg/$(QTDIR64)/include' -I'/Users/keith/source/8755prg/$(QTDIR64)/include/QtCore' -I'/Users/keith/source/8755prg/$(QTDIR64)/include/QtGui' -I'/Users/keith/source/8755prg/$(QTDIR64)/include/QtSerialPort' -I'/Users/keith/source/8755prg/$(QTDIR64)/include/QtWidgets' -I/usr/local/Qt-6.8.0/lib/QtWidgets.framework/Headers -I/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers -I/usr/local/Qt-6.8.0/lib/QtSerialPort.framework/Headers -I/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.8.0/lib guiMainWindow.h -o GeneratedFiles/moc_guiMainWindow.cpp

GeneratedFiles/moc_qLedWidget.cpp: qLedWidget.h \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers/QPainter \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers/qpainter.h \
		GeneratedFiles/moc_predefs.h \
		/usr/local/Qt-6.8.0/libexec/moc
	/usr/local/Qt-6.8.0/libexec/moc $(DEFINES) --include /Users/keith/source/8755prg/GeneratedFiles/moc_predefs.h -I/usr/local/Qt-6.8.0/mkspecs/macx-clang -I/Users/keith/source/8755prg -I/Users/keith/source/8755prg -I/Users/keith/source/8755prg/GeneratedFiles -I'/Users/keith/source/8755prg/$(QTDIR64)/include' -I'/Users/keith/source/8755prg/$(QTDIR64)/include/QtCore' -I'/Users/keith/source/8755prg/$(QTDIR64)/include/QtGui' -I'/Users/keith/source/8755prg/$(QTDIR64)/include/QtSerialPort' -I'/Users/keith/source/8755prg/$(QTDIR64)/include/QtWidgets' -I/usr/local/Qt-6.8.0/lib/QtWidgets.framework/Headers -I/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers -I/usr/local/Qt-6.8.0/lib/QtSerialPort.framework/Headers -I/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.8.0/lib qLedWidget.h -o GeneratedFiles/moc_qLedWidget.cpp

GeneratedFiles/moc_senderthread.cpp: senderthread.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QMutex \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qmutex.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QThread \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QWaitCondition \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qwaitcondition.h \
		GeneratedFiles/moc_predefs.h \
		/usr/local/Qt-6.8.0/libexec/moc
	/usr/local/Qt-6.8.0/libexec/moc $(DEFINES) --include /Users/keith/source/8755prg/GeneratedFiles/moc_predefs.h -I/usr/local/Qt-6.8.0/mkspecs/macx-clang -I/Users/keith/source/8755prg -I/Users/keith/source/8755prg -I/Users/keith/source/8755prg/GeneratedFiles -I'/Users/keith/source/8755prg/$(QTDIR64)/include' -I'/Users/keith/source/8755prg/$(QTDIR64)/include/QtCore' -I'/Users/keith/source/8755prg/$(QTDIR64)/include/QtGui' -I'/Users/keith/source/8755prg/$(QTDIR64)/include/QtSerialPort' -I'/Users/keith/source/8755prg/$(QTDIR64)/include/QtWidgets' -I/usr/local/Qt-6.8.0/lib/QtWidgets.framework/Headers -I/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers -I/usr/local/Qt-6.8.0/lib/QtSerialPort.framework/Headers -I/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.8.0/lib senderthread.h -o GeneratedFiles/moc_senderthread.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: GeneratedFiles/ui_guiMainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) GeneratedFiles/ui_guiMainWindow.h
GeneratedFiles/ui_guiMainWindow.h: guiMainWindow.ui \
		/usr/local/Qt-6.8.0/libexec/uic
	/usr/local/Qt-6.8.0/libexec/uic guiMainWindow.ui -o GeneratedFiles/ui_guiMainWindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

release/hexFile.o: hexFile.cpp hexFile.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qstring.h \
		guiMainWindow.h \
		GeneratedFiles/ui_guiMainWindow.h \
		senderthread.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QMutex \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qmutex.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QThread \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QWaitCondition \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qwaitcondition.h \
		qLedWidget.h \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers/QPainter \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QFile \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/hexFile.o hexFile.cpp

release/guiMainWindow.o: guiMainWindow.cpp guiMainWindow.h \
		GeneratedFiles/ui_guiMainWindow.h \
		hexFile.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qstring.h \
		senderthread.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QMutex \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qmutex.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QThread \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QWaitCondition \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qwaitcondition.h \
		qLedWidget.h \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers/QPainter \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers/qpainter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/guiMainWindow.o guiMainWindow.cpp

release/main.o: main.cpp guiMainWindow.h \
		GeneratedFiles/ui_guiMainWindow.h \
		hexFile.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qstring.h \
		senderthread.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QMutex \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qmutex.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QThread \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QWaitCondition \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qwaitcondition.h \
		qLedWidget.h \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers/QPainter \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers/qpainter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/main.o main.cpp

release/qLedWidget.o: qLedWidget.cpp qLedWidget.h \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers/QPainter \
		/usr/local/Qt-6.8.0/lib/QtGui.framework/Headers/qpainter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/qLedWidget.o qLedWidget.cpp

release/senderthread.o: senderthread.cpp senderthread.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QMutex \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qmutex.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QThread \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QWaitCondition \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qwaitcondition.h \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/QTime \
		/usr/local/Qt-6.8.0/lib/QtCore.framework/Headers/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/senderthread.o senderthread.cpp

release/moc_guiMainWindow.o: GeneratedFiles/moc_guiMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/moc_guiMainWindow.o GeneratedFiles/moc_guiMainWindow.cpp

release/moc_qLedWidget.o: GeneratedFiles/moc_qLedWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/moc_qLedWidget.o GeneratedFiles/moc_qLedWidget.cpp

release/moc_senderthread.o: GeneratedFiles/moc_senderthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/moc_senderthread.o GeneratedFiles/moc_senderthread.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

